site_name: "Engineering Black Book"
site_url: https://example.com/  # Change this to the real value before deploy to prod server
nav: 
    - Home: index.md
    - Git: git/git-collection.md
#theme: readthedocs
theme: 
    name: material
    palette: 
        scheme: default
    features:
        - navigation.instant
